language: node_js

node_js:
- '0.12'

branches:
  only:
  - blog


before_install:
- openssl aes-256-cbc -K $encrypted_a82aff0ff8f8_key -iv $encrypted_a82aff0ff8f8_iv
  -in id_rsa.enc -out id_rsa -d

- chmod 600 ./id_rsa
- eval $(ssh-agent)
- ssh-add ./id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "bb eight"
- git config --global user.email 156516952@qq.com

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save

script:
- cd blog
- hexo clean
- hexo g
- hexo d
